package cn.sdcet.view;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;

import javax.swing.JOptionPane;

import cn.sdcet.dao.Userdao;
import cn.sdcet.dao.Userdao1;
import cn.sdcet.dao.impl.Userdaoimpl;
import cn.sdcet.dao.impl.Userdoimpl1;
import cn.sdcet.db.User;


public class LoginFrame extends javax.swing.JFrame implements ActionListener{

    /**
     * Creates new form NewJFrame
     */
    public LoginFrame() {
        initComponents();
        buttonGroup1.add(jRadioButton1);
        buttonGroup1.add(jRadioButton2);
        jButton1.addActionListener(this);
        jButton2.addActionListener(this);
        jButton3.addActionListener(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jRadioButton1.setText("管理员");

        jRadioButton2.setText("使用者");

        jLabel1.setText("账号");

        jLabel2.setText("密码");

        jButton1.setText("登录");

        jButton2.setText("注册");

        jButton3.setText("取消");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jRadioButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(12, 12, 12)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(13, 13, 13))
        );

        pack();
    }// </editor-fold>                        

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPasswordField jTextField2;
    public void actionPerformed(ActionEvent e) {
    	String str = e.getActionCommand();
    	if ("登录".equals(str)&&jRadioButton1.isSelected()) {
    	
    	denglu1(e);
    	}else if ("登录".equals(str)&&jRadioButton2.isSelected()) {
        	
        	denglu2(e);
        	} else if ("注册".equals(str)&&jRadioButton1.isSelected()){
    	zhuce1(e);
    	} else if ("注册".equals(str)&&jRadioButton2.isSelected()){
        	zhuce2(e);
        	} else if("取消".equals(str)){
    	System.exit(0);
    }
    }
       Userdao ud = new  Userdaoimpl();
    public  void zhuce1(ActionEvent e) {
    	hide();
    	RegistFrame fc = new RegistFrame();
    	fc.setSize(300,250);
        fc.setLocation(200,150);
        fc.setVisible(true);
        fc.setDefaultCloseOperation(EXIT_ON_CLOSE);
    	
    }
    public  void zhuce2(ActionEvent e) {
    	hide();
    	RegistFrame1 fc = new RegistFrame1();
    	fc.setSize(300,250);
        fc.setLocation(200,150);
        fc.setVisible(true);
        fc.setDefaultCloseOperation(EXIT_ON_CLOSE);
    	
    }
    public  void denglu1(ActionEvent e) {
    	
    	User user1 = new User(jTextField1.getText(),jTextField2.getText());

    	boolean flag;
    		try {
    			flag =  ud.login(user1);
    		
    	
    	if (flag) {
    		hide();
    		MainFrame fc = new MainFrame();
            fc.setSize(400,300);
            fc.setLocation(200,150);
            fc.setVisible(true);
            fc.setDefaultCloseOperation(EXIT_ON_CLOSE);
    		
    	} else {
    		JOptionPane.showMessageDialog(jButton1, "用户名或密码错误");
    	}
    		} catch (Exception e1) {
    			
    			e1.printStackTrace();
    		}

    }
    Userdao1 ud1=new Userdoimpl1();
public  void denglu2(ActionEvent e) {
    	
    	User user1 = new User(jTextField1.getText(),jTextField2.getText());

    	boolean flag;
    		try {
    			flag =  ud1.login1(user1);
    		
    	
    	if (flag) {
    		hide();
    		MainFrame1 fc = new MainFrame1();
            fc.setSize(400,300);
            fc.setLocation(200,150);
            fc.setVisible(true);
            fc.setDefaultCloseOperation(EXIT_ON_CLOSE);
    		
    	} else {
    		JOptionPane.showMessageDialog(jButton1, "用户名或密码错误");
    	}
    		} catch (Exception e1) {
    			
    			e1.printStackTrace();
    		}

    }

                   
}


